# Generated by Django 5.2.3 on 2025-06-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('intensidad', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='clases/')),
            ],
        ),
    ]
