# Generated by Django 5.2.3 on 2025-06-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='dia',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], default='lunes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clase',
            name='hora',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clase',
            name='duracion',
            field=models.PositiveIntegerField(),
        ),
    ]
