# Generated by Django 5.2.3 on 2025-06-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_clase_dia_clase_hora_alter_clase_duracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Nutrición', 'Nutrición'), ('Entrenamiento', 'Entrenamiento'), ('Bienestar', 'Bienestar'), ('Motivación', 'Motivación'), ('Equipamiento', 'Equipamiento')], max_length=50)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog/')),
            ],
        ),
    ]
