# Generated by Django 5.2.3 on 2025-06-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.CharField(choices=[('Entrenamiento', 'Entrenamiento'), ('Nutrición', 'Nutrición'), ('Bienestar', 'Bienestar'), ('Motivación', 'Motivación'), ('Equipamiento', 'Equipamiento')], max_length=20),
        ),
    ]
