# Generated by Django 5.2.3 on 2025-07-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_calendario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendario',
            name='instructor',
        ),
    ]
