# Generated by Django 5.2.3 on 2025-07-02 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_remove_calendario_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clase',
            old_name='hora',
            new_name='hora_fin',
        ),
        migrations.AddField(
            model_name='clase',
            name='hora_inicio',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
    ]
